# Site settings
title: 飞仔Felicia
description: 'Foto&Code'
url: 'https://feliciazzz.github.io/'
baseurl:
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: '飞仔Felicia'
  email: zhangfelicia13@gmail.com
  twitter_username: 
 # facebook_username: joshgerdes
  github_username:  feliciazzz
  linkedin_username:  felicia-zhang980427

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
